use customer_behavior1;
select * from customer_b;

-- Q1. What is the Total Revenue Generated by Male vs Female customer..
select gender, sum(purchase_amount) as revenue 
from customer_b
group by gender;

--Q2. Which customer used a discount but still spent more than the average purchase amount..
select customer_id,purchase_amount
from customer_b
where discount_applied='yes' and purchase_amount>=(select avg(purchase_amount) from customer_b);

--Q3. Which are the top 5 products with the highest average review rating..
select Top 5 item_purchased, avg(review_rating) as review_rating from customer_b
group by item_purchased
order by avg(review_rating) desc;

--Q4 Compare the average purchase amount between standard and express shipping..
select shipping_type, AVG(purchase_amount) from customer_b where shipping_type IN ('Standard', 'Express')
group by shipping_type ;

--Q5. Do subscribe customer spend more, compare average spend and total revenue between subscribers and non-subscribers.
SELECT
    subscription_status, count(customer_id),
    AVG(purchase_amount) AS Avg_Spend,
    SUM(purchase_amount) AS Total_Revenue
FROM customer_b
GROUP BY subscription_status
order by Avg_Spend,Total_Revenue  desc;

--Q6. Which 5 products have the highest precentage of purchase with discount applied..
SELECT TOP 5
    item_purchased,
    COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*) 
        AS discount_percentage
FROM customer_b
GROUP BY item_purchased
ORDER BY discount_percentage DESC;

--Q7. segment customer into new, returning , and, loyal based on their total number of previous purchase, and show the count of each segment..
SELECT
    Customer_Segment,
    COUNT(*) AS Customer_Count
FROM (
    SELECT
        CASE
            WHEN previous_purchases <= 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 5 THEN 'Returning'
            ELSE 'Loyal'
        END AS Customer_Segment
    FROM customer_b
) t
GROUP BY Customer_Segment;


--Q8. what are the top 3 most purchase products whithin each category.
WITH item_counts AS (
    SELECT
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (
            PARTITION BY category
            ORDER BY COUNT(customer_id) DESC
        ) AS item_rank
    FROM customer_b
    GROUP BY category, item_purchased
)
SELECT item_rank,category,item_purchased,total_orders
FROM item_counts
WHERE item_rank <= 3;
 
--Q9 are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribes..
select subscription_status, count(customer_id)as repeat_buyers
from customer_b
where previous_purchases>5
group by subscription_status

-- Q10. What is the revenue contribution of each age group..

select age_group, sum(purchase_amount)as total_revenue
from customer_b
group by age_group
order by total_revenue desc;